apiVersion: apps/v1
kind: Deployment
metadata:
  name: vivekas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vivekas
  template:
    metadata:
      labels:
        app: vivekas
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: vivekas-container
          image: loksainadh/vivekas-milk-management:latest
          ports:
            - containerPort: 8080
          